name: Run Selenium Tests

on:
  push:
    branches:
      - main
      - Feature-*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Verify Files
        run: ls -R

      - name: Build and Run Tests
        run: mvn -f pom.xml clean test
